<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WilayahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wilayah')->insert([
            [
                'id_wilayah' => 1,
                'nama_wilayah' => 'Desa Pasir Bolang',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 429,
                'latitude' => -6.22647991797654200,
                'longitude' => 106.47184220102415000,
                'batas_utara' => 'Kecamatan Cikupa',
                'batas_timur' => 'Desa Matagara',
                'batas_barat' => 'Desa Sukanagara (Cikupa)',
                'batas_selatan' => 'Desa Cisereh',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 2,
                'nama_wilayah' => 'Desa Cisereh',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 318,
                'latitude' => -6.23258393623556000,
                'longitude' => 106.45836800354205000,
                'batas_utara' => 'Desa Sentul (Balaraja)',
                'batas_timur' => 'Desa Pasir Bolang',
                'batas_barat' => 'Desa Sentul (Balaraja)',
                'batas_selatan' => 'Desa Pematang',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 3,
                'nama_wilayah' => 'Desa Pasir Nangka',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 392,
                'latitude' => -6.25222566486495700,
                'longitude' => 106.47206608878156000,
                'batas_utara' => 'Desa Pasir Bolang',
                'batas_timur' => 'Kelurahan Tigaraksa',
                'batas_barat' => 'Desa Pematang',
                'batas_selatan' => 'Desa Tegalsari',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 4,
                'nama_wilayah' => 'Desa Pematang',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 268,
                'latitude' => -6.25070022721644800,
                'longitude' => 106.46269611260229000,
                'batas_utara' => 'Desa Cisereh',
                'batas_timur' => 'Desa Pasir Nangka',
                'batas_barat' => 'Desa Pete',
                'batas_selatan' => 'Desa Tegalsari',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 5,
                'nama_wilayah' => 'Desa Pete',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 404,
                'latitude' => -6.25517574675986050,
                'longitude' => 106.46014819401702000,
                'batas_utara' => 'Desa Cisereh',
                'batas_timur' => 'Desa Pematang',
                'batas_barat' => 'Desa Sodong',
                'batas_selatan' => 'Desa Tegalsari',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 6,
                'nama_wilayah' => 'Desa Tegalsari',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 356,
                'latitude' => -6.25950871858672100,
                'longitude' => 106.44606958089086000,
                'batas_utara' => 'Desa Pematang',
                'batas_timur' => 'Desa Pasir Nangka',
                'batas_barat' => 'Desa Pete',
                'batas_selatan' => 'Desa Sodong',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 7,
                'nama_wilayah' => 'Desa Mata Gara',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 390,
                'latitude' => -6.25105207832220700,
                'longitude' => 106.48871237640144000,
                'batas_utara' => 'Desa Marga Sari',
                'batas_timur' => 'Desa Sodong',
                'batas_barat' => 'Desa Pasir Nangka',
                'batas_selatan' => 'Kelurahan Kadu Agung',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 8,
                'nama_wilayah' => 'Desa Marga Sari',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 350,
                'latitude' => -6.28606598874702700,
                'longitude' => 106.49771244628573000,
                'batas_utara' => 'Desa Cileles (Kec. Tigaraksa)',
                'batas_timur' => 'Kelurahan Kadu Agung',
                'batas_barat' => 'Desa Sodong',
                'batas_selatan' => 'Desa Mata Gara',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 9,
                'nama_wilayah' => 'Desa Sodong',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 410,
                'latitude' => -6.28278867934972200,
                'longitude' => 106.46819138548888000,
                'batas_utara' => 'Desa Matagara',
                'batas_timur' => 'Desa Marga Sari',
                'batas_barat' => 'Desa Pete',
                'batas_selatan' => 'Desa Tegalsari',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 10,
                'nama_wilayah' => 'Desa Tapos',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 355,
                'latitude' => -6.29491710259832500,
                'longitude' => 106.47231257584326000,
                'batas_utara' => 'Desa Sodong',
                'batas_timur' => 'Kelurahan Tigaraksa',
                'batas_barat' => 'Desa Tegalsari',
                'batas_selatan' => 'Desa Bantar Panjang',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 11,
                'nama_wilayah' => 'Desa Bantar Panjang',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 578,
                'latitude' => -6.29560118492594800,
                'longitude' => 106.45126923990308000,
                'batas_utara' => 'Desa Tapos',
                'batas_timur' => 'Kelurahan Tigaraksa',
                'batas_barat' => 'Desa Tegalsari',
                'batas_selatan' => 'Desa Cileles',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 12,
                'nama_wilayah' => 'Desa Cileles',
                'jenis_wilayah' => 'Desa',
                'luas_wilayah' => 434,
                'latitude' => -6.32024263025774100,
                'longitude' => 106.43198249092904000,
                'batas_utara' => 'Desa Bantar Panjang',
                'batas_timur' => 'Kelurahan Kadu Agung',
                'batas_barat' => 'Desa Tegalsari',
                'batas_selatan' => 'Kecamatan Solear',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 13,
                'nama_wilayah' => 'Kecamatan Tigaraksa',
                'jenis_wilayah' => 'Kecamatan',
                'luas_wilayah' => 5279,
                'latitude' => null,
                'longitude' => null,
                'batas_utara' => null,
                'batas_timur' => null,
                'batas_barat' => null,
                'batas_selatan' => null,
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 14,
                'nama_wilayah' => 'Kelurahan Kadu Agung',
                'jenis_wilayah' => 'Kelurahan',
                'luas_wilayah' => 284,
                'latitude' => -6.26903958048301800,
                'longitude' => 106.49774425197550000,
                'batas_utara' => 'Desa Mata Gara',
                'batas_timur' => 'Desa Marga Sari',
                'batas_barat' => 'Kelurahan Tigaraksa',
                'batas_selatan' => 'Desa Pasir Nangka',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
            [
                'id_wilayah' => 15,
                'nama_wilayah' => 'Kelurahan Tigaraksa',
                'jenis_wilayah' => 'Kelurahan',
                'luas_wilayah' => 311,
                'latitude' => -6.26416190920571000,
                'longitude' => 106.43198249092904000,
                'batas_utara' => 'Desa Pasir Nangka',
                'batas_timur' => 'Kecamatan Tigaraksa',
                'batas_barat' => 'Desa Cileles',
                'batas_selatan' => 'Desa Pasir Bolang',
                'gambar_wilayah' => 'profilwilayah/petakecamatan.png',
                'updated_by' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
